### ISSUE TITLE
Plugin don't work Apex 5

### ISSUE THREAD

**Issue by alexbunyak** [mortenbra/apex-plugins#3]
i tried to install plugin and get error Invalid Plug-in File.

**Comment by mortenbra** [comment]
Please provide more information:
1. What is your environment (database edition, database version, APEX version, web browser) ?
2. Which plugin did you try to install?
3. What steps did you follow to install it?
4. What error message did you get?

**Comment by alexbunyak** [comment]
About problem:
1. Apex 5.1 Oracle Database 11g Express Edition 11.2 Chrome browser
2. Execute PL/SQL and Return Content plugin
3. In Shared components of Application - Plugins - Import - Choose file - Next - Next 
4. Error "Invalid Plug-in File" "File is not a valid Application Express plug-in export file."

**Comment by mortenbra** [comment]
And which file are you trying to import? It should be the "dynamic_action_plugin_muledev_server_region_refresh.sql" file:

https://github.com/mortenbra/apex-plugins/blob/master/execute-plsql-and-return-content-dynamic-action/plugin/dynamic_action_plugin_muledev_server_region_refresh.sql

**Comment by alexbunyak** [comment]
![1capture](https://user-images.githubusercontent.com/13658083/36025341-616f243c-0d9b-11e8-8edb-21d2087507c7.PNG)
Yes, I use this file

**Comment by alexbunyak** [comment]
I re-download file and everething Ok. Thank you.
